// Copyright 2024 The DriverHub Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef DRIVERHUB_SRC_SHIM_KERNEL_GKI_STUBS_H_
#define DRIVERHUB_SRC_SHIM_KERNEL_GKI_STUBS_H_

// Auto-generated KMI stub declarations for GKI android15-6.6.
// 1394 function stubs + 29 variable stubs.
// Regenerate with: python3 tools/generate_stubs.py

#ifdef __cplusplus
extern "C" {
#endif

void __ClearPageMovable(struct page *page);
void __SetPageMovable(struct page *page, const struct movable_operations *ops);
int ___pskb_trim(struct sk_buff *skb, unsigned int len);
int ___ratelimit(struct ratelimit_state *rs, const char *func);
return __alloc_pages(gfp_mask, order, nid, NULL);
void __percpu *__alloc_percpu(size_t size, size_t align);
return __alloc_percpu_gfp(size, align, flags);
return __alloc_skb(size, priority, 0, NUMA_NO_NODE);
struct gendisk *__blk_alloc_disk(int node, struct lock_class_key *lkclass);
return __blk_rq_map_sg(q, rq, sglist, &last_sg);
int __clk_determine_rate(struct clk_hw *core, struct clk_rate_request *req);
void __const_udelay(unsigned long xloops);
void __cpuhp_remove_state(enum cpuhp_state state, bool invoke);
return __cpuhp_setup_state(state, name, true, startup, teardown, false);
unsigned long __crypto_memneq(const void *a, const void *b, size_t size);
struct fwnode_handle *__dev_fwnode(struct device *dev);
struct net_device *__dev_get_by_index(struct net *net, int ifindex);
struct net_device *__dev_get_by_name(struct net *net, const char *name);
int __dev_queue_xmit(struct sk_buff *skb, struct net_device *sb_dev);
unsigned long __fdget(unsigned int fd);
void __flush_workqueue(struct workqueue_struct *wq);
void __folio_put(struct folio *folio);
void __free_pages(struct page *page, unsigned int order);
char *__get_task_comm(char *to, size_t len, struct task_struct *tsk);
return __hw_addr_sync_dev(&dev->uc, dev, sync, unsync);
struct net_device *__ip_dev_find(struct net *net, __be32 addr, bool devref);
void __ip_select_ident(struct net *net, struct iphdr *iph, int segs);
int __ipv6_addr_type(const struct in6_addr *addr);
void __kfifo_free(struct __kfifo *fifo);
return __kunit_add_resource(test, init, free, res, data);
void __local_bh_enable_ip(unsigned long ip, unsigned int cnt);
int __mdiobus_register(struct mii_bus *bus, struct module *owner);
void __module_get(struct module *module);
unsigned long __msecs_to_jiffies(const unsigned int m);
return __napi_alloc_skb(napi, length, GFP_ATOMIC);
void __napi_schedule(struct napi_struct *n);
return __netdev_alloc_skb(dev, length, GFP_ATOMIC);
void __netif_napi_del(struct napi_struct *napi);
int __netif_rx(struct sk_buff *skb);
return __netlink_dump_start(ssk, skb, nlh, control);
return __nlmsg_put(skb, portid, seq, type, payload, flags);
bool __percpu_down_read(struct percpu_rw_semaphore *, bool);
void __pm_runtime_disable(struct device *dev, bool check_resume);
int __pm_runtime_idle(struct device *dev, int rpmflags);
int __pm_runtime_resume(struct device *dev, int rpmflags);
int __pm_runtime_suspend(struct device *dev, int rpmflags);
int __printk_ratelimit(const char *func);
return __pskb_copy_fclone(skb, headroom, gfp_mask, false);
void *__pskb_pull_tail(struct sk_buff *skb, int delta);
void __put_cred(struct cred *);
void __put_net(struct net *net);
void __put_task_struct(struct task_struct *t);
return __register_chrdev(major, 0, 256, name, fops);
int __request_module(bool wait, const char *name, ...);
void __sk_flush_backlog(struct sock *sk);
void __sk_mem_reclaim(struct sock *sk, int amount);
return __sk_receive_skb(sk, skb, nested, 1, true);
int __skb_pad(struct sk_buff *skb, int pad, bool free_on_error);
int __sock_queue_rcv_skb(struct sock *sk, struct sk_buff *skb);
void __sock_tx_timestamp(__u16 tsflags, __u8 *tx_flags);
int __srcu_read_lock(struct srcu_struct *ssp);
void __srcu_read_unlock(struct srcu_struct *ssp, int idx);
int __sysfs_match_string(const char * const *array, size_t n, const char *s);
void __tasklet_schedule(struct tasklet_struct *t);
unsigned long __usecs_to_jiffies(const unsigned int u);
void *__vmalloc(unsigned long size, gfp_t gfp_mask);
void __wake_up_sync_key(struct wait_queue_head *wq_head, unsigned int mode, void *key);
size_t _copy_from_iter(void *addr, size_t bytes, struct iov_iter *i);
size_t _copy_to_iter(const void *addr, size_t bytes, struct iov_iter *i);
void _dev_notice(const struct device *dev, const char *fmt, ...);
unsigned long _find_first_bit(const unsigned long *addr, unsigned long size);
unsigned long _find_first_zero_bit(const unsigned long *addr, unsigned long size);
return _find_next_bit(addr, size, offset);
return _find_next_zero_bit(addr, size, offset);
struct proc_dir_entry *_proc_mkdir(const char *, umode_t, struct proc_dir_entry *, void *, bool);
int __lockfunc _raw_spin_trylock(raw_spinlock_t *lock);
int __lockfunc _raw_spin_trylock_bh(raw_spinlock_t *lock);
void __lockfunc _raw_spin_unlock_irq(raw_spinlock_t *lock);
void __lockfunc _raw_write_lock(rwlock_t *lock);
void __lockfunc _raw_write_unlock(rwlock_t *lock);
void add_taint(unsigned flag, enum lockdep_ok);
void aes_encrypt(const struct crypto_aes_ctx *ctx, u8 *out, const u8 *in);
void all_vm_events(unsigned long *);
struct sk_buff *alloc_can_skb(struct net_device *dev, struct can_frame **cf);
void *alloc_pages_exact(size_t size, gfp_t gfp_mask);
void arc4_crypt(struct arc4_ctx *ctx, u8 *out, const u8 *in, unsigned int len);
int arc4_setkey(struct arc4_ctx *ctx, const u8 *in_key, unsigned int key_len);
struct page *balloon_page_alloc(void);
struct page *balloon_page_dequeue(struct balloon_dev_info *b_dev_info);
void baswap(bdaddr_t *dst, const bdaddr_t *src);
int bcmp(const void *,const void *,__kernel_size_t);
char *bin2hex(char *dst, const void *src, size_t count);
return bio_alloc_bioset(bdev, nr_vecs, opf, gfp_mask, &fs_bio_set);
void bio_chain(struct bio *, struct bio *);
unsigned long bio_start_io_acct(struct bio *bio);
int bit_wait(struct wait_bit_key *key, int mode);
int bit_wait_timeout(struct wait_bit_key *key, int mode);
blk_status_t blk_execute_rq(struct request *rq, bool at_head);
void blk_mq_freeze_queue(struct request_queue *q);
void blk_mq_stop_hw_queue(struct blk_mq_hw_ctx *hctx);
void blk_mq_unfreeze_queue(struct request_queue *q);
void blk_queue_io_min(struct request_queue *q, unsigned int min);
void blk_queue_io_opt(struct request_queue *q, unsigned int opt);
void blk_queue_write_cache(struct request_queue *q, bool enabled, bool fua);
int blk_status_to_errno(blk_status_t status);
void blkdev_put(struct block_device *bdev, void *holder);
void bpf_trace_run1(struct bpf_prog *prog, u64 arg1);
void bpf_trace_run2(struct bpf_prog *prog, u64 arg1, u64 arg2);
struct sock *bt_accept_dequeue(struct sock *parent, struct socket *newsock);
void bt_accept_enqueue(struct sock *parent, struct sock *sk, bool bh);
void bt_accept_unlink(struct sock *sk);
void bt_err(const char *fmt, ...);
void bt_info(const char *fmt, ...);
void bt_procfs_cleanup(struct net *net, const char *name);
int bt_sock_ioctl(struct socket *sock, unsigned int cmd, unsigned long arg);
void bt_sock_link(struct bt_sock_list *l, struct sock *s);
__poll_t bt_sock_poll(struct file *file, struct socket *sock, poll_table *wait);
int bt_sock_register(int proto, const struct net_proto_family *ops);
void bt_sock_unlink(struct bt_sock_list *l, struct sock *s);
void bt_sock_unregister(int proto);
int bt_sock_wait_ready(struct sock *sk, unsigned int msg_flags);
int bt_sock_wait_state(struct sock *sk, int state, unsigned long timeo);
void bt_warn(const char *fmt, ...);
int bus_register(const struct bus_type *bus);
void bus_unregister(const struct bus_type *bus);
void can_bus_off(struct net_device *dev);
int can_change_mtu(struct net_device *dev, int new_mtu);
int can_proto_register(const struct can_proto *cp);
void can_proto_unregister(const struct can_proto *cp);
int can_send(struct sk_buff *skb, int loop);
bool cancel_work(struct work_struct *work);
return check_zeroed_user(src.user + offset, size);
void class_dev_iter_exit(struct class_dev_iter *iter);
struct device *class_dev_iter_next(struct class_dev_iter *iter);
return class_find_device(class, NULL, name, device_match_name);
void cleanup_srcu_struct(struct srcu_struct *ssp);
struct clk *clk_get_parent(struct clk *clk);
bool clk_has_parent(const struct clk *clk, const struct clk *parent);
struct clk *clk_hw_get_clk(struct clk_hw *hw, const char *con_id);
int clk_hw_register(struct device *dev, struct clk_hw *hw);
void clk_hw_unregister(struct clk_hw *hw);
bool clk_is_match(const struct clk *p, const struct clk *q);
int clk_notifier_register(struct clk *clk, struct notifier_block *nb);
int clk_set_parent(struct clk *clk, struct clk *parent);
int clk_set_rate_range(struct clk *clk, unsigned long min, unsigned long max);
void close_candev(struct net_device *dev);
void consume_skb(struct sk_buff *skb);
u16 crc16(u16 crc, const u8 *buffer, size_t len);
u32 crc32_le(u32 crc, unsigned char const *p, size_t len);
u16 crc_ccitt(u16 crc, const u8 *buffer, size_t len);
int crypto_aead_decrypt(struct aead_request *req);
int crypto_aead_encrypt(struct aead_request *req);
struct crypto_aead *crypto_alloc_aead(const char *alg_name, u32 type, u32 mask);
struct crypto_tfm *crypto_alloc_base(const char *alg_name, u32 type, u32 mask);
struct crypto_kpp *crypto_alloc_kpp(const char *alg_name, u32 type, u32 mask);
void crypto_destroy_tfm(void *mem, struct crypto_tfm *tfm);
unsigned int crypto_ecdh_key_len(const struct ecdh *params);
int crypto_has_ahash(const char *alg_name, u32 type, u32 mask);
int crypto_has_alg(const char *name, u32 type, u32 mask);
void crypto_req_done(void *req, int err);
int crypto_shash_final(struct shash_desc *desc, u8 *out);
return csum_ipv6_magic(saddr, daddr, len, IPPROTO_TCP, base);
struct work_struct *current_work(void);
bool debugfs_initialized(void);
struct dentry *debugfs_lookup(const char *name, struct dentry *parent);
void dec_zone_page_state(struct page *, enum zone_stat_item);
loff_t default_llseek(struct file *file, loff_t offset, int whence);
int default_wake_function(struct wait_queue_entry *wq_entry, unsigned mode, int flags, void *key);
void dev_add_pack(struct packet_type *pt);
int dev_alloc_name(struct net_device *dev, const char *name);
void dev_close_many(struct list_head *head, bool unlink);
int dev_err_probe(const struct device *dev, int err, const char *fmt, ...);
struct net_device *dev_get_by_index(struct net *net, int ifindex);
struct net_device *dev_get_by_index_rcu(struct net *net, int ifindex);
struct net_device *dev_get_by_name(struct net *net, const char *name);
unsigned int dev_get_flags(const struct net_device *);
void dev_get_tstats64(struct net_device *dev, struct rtnl_link_stats64 *s);
struct net_device *dev_getfirstbyhwtype(struct net *net, unsigned short type);
void dev_load(struct net *net, const char *name);
int dev_mc_sync(struct net_device *to, struct net_device *from);
void dev_mc_unsync(struct net_device *to, struct net_device *from);
bool dev_nit_active(struct net_device *dev);
void dev_remove_pack(struct packet_type *pt);
int dev_set_allmulti(struct net_device *dev, int inc);
int dev_set_mtu(struct net_device *, int);
int dev_set_promiscuity(struct net_device *dev, int inc);
return dev_uc_add(macvlan->lowerdev, dev->dev_addr);
int dev_uc_add_excl(struct net_device *dev, const unsigned char *addr);
int dev_uc_del(struct net_device *dev, const unsigned char *addr);
int dev_uc_sync(struct net_device *to, struct net_device *from);
void dev_uc_unsync(struct net_device *to, struct net_device *from);
return device_add_disk(NULL, disk, NULL);
struct device *device_find_any_child(struct device *parent);
const void *device_get_match_data(const struct device *dev);
int device_match_name(struct device *dev, const void *name);
int device_register(struct device *dev);
int device_rename(struct device *dev, const char *new_name);
void device_unregister(struct device *dev);
int device_wakeup_disable(struct device *dev);
int device_wakeup_enable(struct device *dev);
void devm_clk_put(struct device *dev, struct clk *clk);
void devm_free_irq(struct device *dev, unsigned int irq, void *dev_id);
int devm_hwrng_register(struct device *dev, struct hwrng *rng);
void devm_kfree(struct device *dev, const void *p);
void devm_memunmap(struct device *dev, void *addr);
void disk_set_zoned(struct gendisk *disk, enum blk_zoned_model model);
return dma_alloc_attrs(dev, size, dma_addr, gfp, attrs);
return dma_free_attrs(dev, size, cpu_addr, dma_handle, 0);
void down_read(struct rw_semaphore *sem);
void down_write(struct rw_semaphore *sem);
void dput(struct dentry *);
void drain_workqueue(struct workqueue_struct *wq);
int driver_attach(struct device_driver *drv);
int driver_register(struct device_driver *drv);
return driver_unregister(&sdriver->driver);
void dst_cache_destroy(struct dst_cache *dst_cache);
struct dst_entry *dst_cache_get(struct dst_cache *dst_cache);
void dst_release(struct dst_entry *dst);
int eth_header_parse(const struct sk_buff *skb, unsigned char *haddr);
int eth_mac_addr(struct net_device *dev, void *p);
__be16 eth_type_trans(struct sk_buff *skb, struct net_device *dev);
int eth_validate_addr(struct net_device *dev);
void ether_setup(struct net_device *dev);
u32 ethtool_op_get_link(struct net_device *dev);
void eventfd_ctx_do_read(struct eventfd_ctx *ctx, __u64 *cnt);
struct eventfd_ctx *eventfd_ctx_fdget(int fd);
struct eventfd_ctx *eventfd_ctx_fileget(struct file *file);
void eventfd_ctx_put(struct eventfd_ctx *ctx);
__u64 eventfd_signal(struct eventfd_ctx *ctx, __u64 n);
int fasync_helper(int, struct file *, int, struct fasync_struct **);
struct file *fget(unsigned int fd);
char *file_path(struct file *, char *, int);
int filp_close(struct file *, fl_owner_t id);
struct file *filp_open_block(const char *, int, umode_t);
void finish_rcuwait(struct rcuwait *w);
bool flush_delayed_work(struct delayed_work *dwork);
void folio_wait_bit(struct folio *folio, int bit_nr);
void fput(struct file *);
void fqdir_exit(struct fqdir *fqdir);
int fqdir_init(struct fqdir **fqdirp, struct inet_frags *f, struct net *net);
void free_candev(struct net_device *dev);
void free_pages(unsigned long addr, unsigned int order);
void free_pages_exact(void *virt, size_t size);
void free_percpu(void __percpu *__pdata);
return genl_register_family(&ZZZ_genl_family);
int genphy_resume(struct phy_device *phydev);
struct net *get_net_ns_by_fd(int fd);
struct net *get_net_ns_by_pid(pid_t pid);
u32 get_random_u32(void);
int get_user_ifreq(struct ifreq *ifr, void __user **ifrdata, void __user *arg);
unsigned long get_zeroed_page(gfp_t gfp_mask);
bool glob_match(char const *pat, char const *str);
void *gpiochip_get_data(struct gpio_chip *gc);
int gre_add_protocol(const struct gre_protocol *proto, u8 version);
int gre_del_protocol(const struct gre_protocol *proto, u8 version);
void gro_cells_destroy(struct gro_cells *gcells);
int gro_cells_init(struct gro_cells *gcells, struct net_device *dev);
int gro_cells_receive(struct gro_cells *gcells, struct sk_buff *skb);
struct hci_dev *hci_alloc_dev_priv(int sizeof_priv);
int hci_conn_check_secure(struct hci_conn *conn, __u8 sec_level);
int hci_conn_switch_role(struct hci_conn *conn, __u8 role);
int hci_devcd_abort(struct hci_dev *hdev);
int hci_devcd_append(struct hci_dev *hdev, struct sk_buff *skb);
int hci_devcd_complete(struct hci_dev *hdev);
int hci_devcd_init(struct hci_dev *hdev, u32 dump_size);
void hci_free_dev(struct hci_dev *hdev);
struct hci_dev *hci_get_route(bdaddr_t *dst, bdaddr_t *src, u8 src_type);
int hci_recv_diag(struct hci_dev *hdev, struct sk_buff *skb);
int hci_recv_frame(struct hci_dev *hdev, struct sk_buff *skb);
int hci_register_cb(struct hci_cb *hcb);
int hci_register_dev(struct hci_dev *hdev);
int hci_reset_dev(struct hci_dev *hdev);
void hci_set_fw_info(struct hci_dev *hdev, const char *fmt, ...);
int hci_unregister_cb(struct hci_cb *hcb);
void hci_unregister_dev(struct hci_dev *hdev);
int hex2bin(u8 *dst, const char *src, size_t count);
int hex_to_bin(unsigned char ch);
int hid_add_device(struct hid_device *);
struct hid_device *hid_allocate_device(void);
void hid_destroy_device(struct hid_device *);
bool hid_ignore(struct hid_device *);
bool hid_is_usb(const struct hid_device *hdev);
int hid_parse_report(struct hid_device *hid, __u8 *start, unsigned size);
bool hrtimer_active(const struct hrtimer *timer);
int hrtimer_cancel(struct hrtimer *timer);
int ida_alloc_range(struct ida *, unsigned int min, unsigned int max, gfp_t);
void ida_destroy(struct ida *ida);
void ida_free(struct ida *, unsigned int id);
int idr_alloc(struct idr *, void *ptr, int start, int end, gfp_t);
void idr_destroy(struct idr *);
void *idr_find(const struct idr *, unsigned long id);
void *idr_get_next(struct idr *, int *nextid);
void *idr_get_next_ul(struct idr *, unsigned long *nextid);
void idr_preload(gfp_t gfp_mask);
void *idr_remove(struct idr *, unsigned long id);
void *idr_replace(struct idr *, void *, unsigned long id);
int ieee802154_hdr_peek(const struct sk_buff *skb, struct ieee802154_hdr *hdr);
int ieee802154_hdr_pull(struct sk_buff *skb, struct ieee802154_hdr *hdr);
int ieee802154_hdr_push(struct sk_buff *skb, struct ieee802154_hdr *hdr);
ssize_t iio_format_value(char *buf, unsigned int type, int size, int *vals);
__be32 in_aton(const char *str);
void inc_zone_page_state(struct page *, enum zone_stat_item);
int inet6_csk_xmit(struct sock *sk, struct sk_buff *skb, struct flowi *fl);
void inet_frag_destroy(struct inet_frag_queue *q);
struct inet_frag_queue *inet_frag_find(struct fqdir *fqdir, void *key);
void inet_frag_kill(struct inet_frag_queue *q);
void inet_frags_fini(struct inet_frags *);
int inet_frags_init(struct inet_frags *);
int init_srcu_struct(struct srcu_struct *ssp);
int iov_iter_npages(const struct iov_iter *i, int maxpages);
void iov_iter_revert(struct iov_iter *i, size_t bytes);
int ip6_dst_hoplimit(struct dst_entry *dst);
int ip_local_out(struct net *net, struct sock *sk, struct sk_buff *skb);
int ip_mc_join_group(struct sock *sk, struct ip_mreqn *imr);
int ip_queue_xmit(struct sock *sk, struct sk_buff *skb, struct flowi *fl);
return ip_route_output_flow(net, flp, NULL);
void ip_send_check(struct iphdr *ip);
struct irq_data *irq_get_irq_data(unsigned int irq);
int irq_set_irq_wake(unsigned int irq, unsigned int on);
unsigned int jiffies_to_msecs(const unsigned long j);
unsigned int jiffies_to_usecs(const unsigned long j);
char *kasprintf(gfp_t gfp, const char *fmt, ...);
int kernel_accept(struct socket *sock, struct socket **newsock, int flags);
int kernel_bind(struct socket *sock, struct sockaddr *addr, int addrlen);
int kernel_listen(struct socket *sock, int backlog);
ssize_t kernel_read(struct file *, void *, size_t, loff_t *);
int kernel_sock_shutdown(struct socket *sock, enum sock_shutdown_cmd how);
ssize_t kernel_write(struct file *, const void *, size_t, loff_t *);
void kfree_const(const void *x);
void kfree_sensitive(const void *objp);
void kfree_skb_partial(struct sk_buff *skb, bool head_stolen);
void kill_fasync(struct fasync_struct **, int, int);
return kmalloc_large(size, flags);
return kmalloc_large_node(size, flags, node);
return kmem_cache_alloc(jbd2_inode_cache, gfp_flags);
void kmem_cache_destroy(struct kmem_cache *s);
void kmem_cache_free(struct kmem_cache *s, void *objp);
struct kobject *kobject_get(struct kobject *kobj);
char *kstrndup(const char *s, size_t len, gfp_t gfp);
int kstrtobool_from_user(const char __user *s, size_t count, bool *res);
int kstrtoll(const char *s, unsigned int base, long long *res);
int kstrtou16(const char *s, unsigned int base, u16 *res);
int kstrtou8(const char *s, unsigned int base, u8 *res);
bool kthread_should_stop(void);
int kthread_stop(struct task_struct *k);
void ktime_get_real_ts64(struct timespec64 *tv);
void ktime_get_snapshot(struct system_time_snapshot *systime_snapshot);
void ktime_get_ts64(struct timespec64 *ts);
ktime_t ktime_get_with_offset(enum tk_offsets offs);
int kunit_add_action(struct kunit *test, kunit_action_t *action, void *ctx);
void kunit_cleanup(struct kunit *test);
void kunit_init_test(struct kunit *test, const char *name, char *log);
void kunit_remove_resource(struct kunit *test, struct kunit_resource *res);
void kunit_try_catch_run(struct kunit_try_catch *try_catch, void *context);
void __noreturn kunit_try_catch_throw(struct kunit_try_catch *try_catch);
const char *kvasprintf_const(gfp_t gfp, const char *fmt, va_list args);
void kvfree(const void *addr);
void kvfree_call_rcu(struct rcu_head *head, void *ptr);
void *kvmalloc_node(size_t size, gfp_t flags, int node);
struct l2cap_conn *l2cap_conn_get(struct l2cap_conn *conn);
void l2cap_conn_put(struct l2cap_conn *conn);
bool l2cap_is_socket(struct socket *sock);
int l2cap_register_user(struct l2cap_conn *conn, struct l2cap_user *user);
void l2cap_unregister_user(struct l2cap_conn *conn, struct l2cap_user *user);
void linkwatch_fire_event(struct net_device *dev);
void list_sort(void *priv, struct list_head *head, list_cmp_func_t cmp);
void lock_sock_nested(struct sock *sk, int subclass);
int match_int(substring_t *, int *result);
char *match_strdup(const substring_t *);
int match_token(char *, const match_table_t table, substring_t args[]);
struct mii_bus *mdiobus_alloc_size(size_t size);
void mdiobus_free(struct mii_bus *bus);
struct phy_device *mdiobus_get_phy(struct mii_bus *bus, int addr);
void mdiobus_unregister(struct mii_bus *bus);
void * memchr(const void *,int,__kernel_size_t);
void *memchr_inv(const void *s, int c, size_t n);
void *memdup_user(const void __user *, size_t);
unsigned long long memparse(const char *ptr, char **retptr);
void * memscan(void *,int,__kernel_size_t);
void *memset64(uint64_t *, uint64_t, __kernel_size_t);
void mii_ethtool_gset(struct mii_if_info *mii, struct ethtool_cmd *ecmd);
int mii_link_ok (struct mii_if_info *mii);
int mii_nway_restart (struct mii_if_info *mii);
return mtree_load(&mm->mm_mt, addr);
bool mutex_is_locked(struct mutex *lock);
bool napi_complete_done(struct napi_struct *n, int work_done);
void napi_disable(struct napi_struct *n);
void napi_enable(struct napi_struct *n);
gro_result_t napi_gro_receive(struct napi_struct *napi, struct sk_buff *skb);
bool napi_schedule_prep(struct napi_struct *n);
void neigh_destroy(struct neighbour *neigh);
int net_ratelimit(void);
void netdev_err(const struct net_device *dev, const char *format, ...);
void netdev_info(const struct net_device *dev, const char *format, ...);
bool netdev_name_in_use(struct net *net, const char *name);
void netdev_notice(const struct net_device *dev, const char *format, ...);
void netdev_warn(const struct net_device *dev, const char *format, ...);
void netif_carrier_off(struct net_device *dev);
void netif_carrier_on(struct net_device *dev);
void netif_device_attach(struct net_device *dev);
void netif_device_detach(struct net_device *dev);
int netif_receive_skb(struct sk_buff *skb);
int netif_rx(struct sk_buff *skb);
void netif_tx_lock(struct net_device *dev);
void netif_tx_unlock(struct net_device *dev);
void netif_tx_wake_queue(struct netdev_queue *dev_queue);
bool netlink_capable(const struct sk_buff *skb, int cap);
bool netlink_net_capable(const struct sk_buff *skb, int cap);
int netlink_unicast(struct sock *ssk, struct sk_buff *skb, __u32 portid, int nonblock);
char *next_arg(char *args, char **param, char **val);
void nf_conntrack_destroy(struct nf_conntrack *nfct);
int nla_memcpy(void *dest, const struct nlattr *src, int count);
int nla_put(struct sk_buff *skb, int attrtype, int attrlen, const void *data);
ssize_t nla_strscpy(char *dst, const struct nlattr *nla, size_t dstsize);
int nonseekable_open(struct inode * inode, struct file * filp);
bool ns_capable(struct user_namespace *ns, int cap);
struct timespec64 ns_to_timespec64(s64 nsec);
int of_irq_get_byname(struct device_node *dev, const char *name);
int open_candev(struct net_device *dev);
void p9_client_cb(struct p9_client *c, struct p9_req_t *req, int status);
int p9_req_put(struct p9_client *c, struct p9_req_t *r);
struct p9_req_t *p9_tag_lookup(struct p9_client *c, u16 tag);
bool pci_device_is_present(struct pci_dev *pdev);
void pci_disable_device(struct pci_dev *dev);
void pci_disable_sriov(struct pci_dev *dev);
int pci_enable_device(struct pci_dev *dev);
int pci_enable_sriov(struct pci_dev *dev, int nr_virtfn);
u8 pci_find_capability(struct pci_dev *dev, int cap);
void pci_free_irq_vectors(struct pci_dev *dev);
void __iomem *pci_iomap(struct pci_dev *dev, int bar, unsigned long max);
void pci_iounmap(struct pci_dev *dev, void __iomem *);
const struct cpumask *pci_irq_get_affinity(struct pci_dev *pdev, int vec);
int pci_irq_vector(struct pci_dev *dev, unsigned int nr);
int pci_read_config_byte(const struct pci_dev *dev, int where, u8 *val);
int pci_read_config_dword(const struct pci_dev *dev, int where, u32 *val);
int pci_read_config_word(const struct pci_dev *dev, int where, u16 *val);
void pci_release_region(struct pci_dev *, int);
int pci_request_region(struct pci_dev *, int, const char *);
void pci_set_master(struct pci_dev *dev);
void pci_unregister_driver(struct pci_driver *dev);
int pci_vfs_assigned(struct pci_dev *dev);
void percpu_down_write(struct percpu_rw_semaphore *);
void percpu_free_rwsem(struct percpu_rw_semaphore *);
void percpu_up_write(struct percpu_rw_semaphore *);
void *perf_trace_buf_alloc(int size, struct pt_regs **regs, int *rctxp);
void phy_attached_info(struct phy_device *phydev);
void phy_disconnect(struct phy_device *phydev);
int phy_do_ioctl_running(struct net_device *dev, struct ifreq *ifr, int cmd);
void phy_print_status(struct phy_device *phydev);
void phy_start(struct phy_device *phydev);
void phy_stop(struct phy_device *phydev);
int phy_suspend(struct phy_device *phydev);
int phylink_connect_phy(struct phylink *, struct phy_device *);
void phylink_destroy(struct phylink *);
void phylink_resume(struct phylink *pl);
void phylink_start(struct phylink *);
void phylink_stop(struct phylink *);
void phylink_suspend(struct phylink *pl, bool mac_wol);
pid_t pid_vnr(struct pid *pid);
void pipe_lock(struct pipe_inode_info *);
void pipe_unlock(struct pipe_inode_info *);
int posix_clock_register(struct posix_clock *clk, struct device *dev);
int ppp_channel_index(struct ppp_channel *);
char *ppp_dev_name(struct ppp_channel *);
void ppp_input(struct ppp_channel *, struct sk_buff *);
int ppp_register_channel(struct ppp_channel *);
int pppox_compat_ioctl(struct socket *sock, unsigned int cmd, unsigned long arg);
int pppox_ioctl(struct socket *sock, unsigned int cmd, unsigned long arg);
void pppox_unbind_sock(struct sock *sk);
void pps_unregister_source(struct pps_device *pps);
int proc_dointvec_jiffies(struct ctl_table *, int, void *, size_t *, loff_t *);
int proc_dointvec_minmax(struct ctl_table *, int, void *, size_t *, loff_t *);
int proto_register(struct proto *prot, int alloc_slab);
void proto_unregister(struct proto *prot);
int pskb_expand_head(struct sk_buff *skb, int nhead, int ntail, gfp_t gfp_mask);
void *pskb_put(struct sk_buff *skb, struct sk_buff *tail, int len);
int ptp_clock_unregister(struct ptp_clock *ptp);
int put_cmsg(struct msghdr*, int level, int type, int len, void *data);
void put_pid(struct pid *pid);
int put_user_ifreq(struct ifreq *ifr, void __user *arg);
int radix_tree_tagged(const struct radix_tree_root *, unsigned int tag);
void rb_erase(struct rb_node *, struct rb_root *);
struct rb_node *rb_first(const struct rb_root *);
struct rb_node *rb_first_postorder(const struct rb_root *);
void rb_insert_color(struct rb_node *, struct rb_root *);
struct rb_node *rb_next_postorder(const struct rb_node *);
bool rcuref_get_slowpath(rcuref_t *ref);
int rcuwait_wake_up(struct rcuwait *w);
void recalc_sigpending(void);
bool refcount_dec_if_one(refcount_t *r);
void regcache_cache_bypass(struct regmap *map, bool enable);
void regcache_cache_only(struct regmap *map, bool enable);
void regcache_mark_dirty(struct regmap *map);
bool regcache_reg_cached(struct regmap *map, unsigned int reg);
int regcache_sync(struct regmap *map);
int register_candev(struct net_device *dev);
int register_netdevice(struct net_device *dev);
int register_oom_notifier(struct notifier_block *nb);
int register_pm_notifier(struct notifier_block *nb);
int register_pppox_proto(int proto_num, const struct pppox_proto *pp);
return regmap_bulk_read(map, reg, buf, count);
return regmap_bulk_write(map, reg, buf, count);
void regmap_exit(struct regmap *map);
return regmap_raw_write(da9055->regmap, reg, val, reg_cnt);
return regmap_write(tps->rmap, reg, val);
void release_firmware(const struct firmware *fw);
void release_sock(struct sock *sk);
bool rfkill_blocked(struct rfkill *rfkill);
void rfkill_destroy(struct rfkill *rfkill);
int rfkill_register(struct rfkill *rfkill);
void rfkill_unregister(struct rfkill *rfkill);
void rhashtable_destroy(struct rhashtable *ht);
return rhashtable_walk_enter(&hlt->ht, iter);
void rhashtable_walk_exit(struct rhashtable_iter *iter);
void *rhashtable_walk_next(struct rhashtable_iter *iter);
void rhashtable_walk_stop(struct rhashtable_iter *iter);
unsigned long round_jiffies(unsigned long j);
int rtc_month_days(unsigned int month, unsigned int year);
u8 rtl8152_get_version(struct usb_interface *intf);
int rtnl_is_locked(void);
int rtnl_link_register(struct rtnl_link_ops *ops);
void rtnl_link_unregister(struct rtnl_link_ops *ops);
void rtnl_lock(void);
void rtnl_unlock(void);
int rtnl_unregister(int protocol, int msgtype);
void rtnl_unregister_all(int protocol);
long schedule_timeout(long timeout);
int scnprintf(char *buf, size_t size, const char *fmt, ...);
void sdio_claim_host(struct sdio_func *func);
int sdio_claim_irq(struct sdio_func *func, sdio_irq_handler_t *handler);
int sdio_disable_func(struct sdio_func *func);
int sdio_enable_func(struct sdio_func *func);
u8 sdio_readb(struct sdio_func *func, unsigned int addr, int *err_ret);
int sdio_register_driver(struct sdio_driver *);
void sdio_release_host(struct sdio_func *func);
int sdio_release_irq(struct sdio_func *func);
void security_sk_clone(const struct sock *sk, struct sock *newsk);
void security_sock_graft(struct sock*sk, struct socket *parent);
void serdev_device_close(struct serdev_device *);
int serdev_device_open(struct serdev_device *);
void set_disk_ro(struct gendisk *disk, bool read_only);
void set_page_private(struct page *page, unsigned long private);
void set_user_nice(struct task_struct *p, long nice);
void sg_init_one(struct scatterlist *, const void *, unsigned int);
void sg_init_table(struct scatterlist *, unsigned int);
int sg_nents(struct scatterlist *sg);
struct scatterlist *sg_next(struct scatterlist *);
long si_mem_available(void);
void si_meminfo(struct sysinfo * val);
return simple_attr_open(inode, file, __get, __set, __fmt);
int simple_attr_release(struct inode *inode, struct file *file);
int simple_open(struct inode *inode, struct file *file);
bool sk_capable(const struct sock *sk, int cap);
void sk_common_release(struct sock *sk);
void sk_error_report(struct sock *sk);
int sk_filter_trim_cap(struct sock *sk, struct sk_buff *skb, unsigned int cap);
void sk_free(struct sock *sk);
int sk_ioctl(struct sock *sk, unsigned int cmd, void __user *arg);
int sk_msg_free(struct sock *sk, struct sk_msg *msg);
int sk_msg_free_nocharge(struct sock *sk, struct sk_msg *msg);
void sk_msg_free_partial(struct sock *sk, struct sk_msg *msg, u32 bytes);
void sk_msg_return_zero(struct sock *sk, struct sk_msg *msg, int bytes);
void sk_msg_trim(struct sock *sk, struct sk_msg *msg, int len);
void sk_psock_drop(struct sock *sk, struct sk_psock *psock);
void sk_setup_caps(struct sock *sk, struct dst_entry *dst);
void sk_stop_timer(struct sock *sk, struct timer_list *timer);
int sk_stream_error(struct sock *sk, int flags, int err);
int sk_stream_wait_memory(struct sock *sk, long *timeo_p);
int skb_checksum_help(struct sk_buff *skb);
struct sk_buff *skb_copy(const struct sk_buff *skb, gfp_t priority);
int skb_copy_bits(const struct sk_buff *skb, int offset, void *to, int len);
void skb_copy_header(struct sk_buff *new, const struct sk_buff *old);
int skb_cow_data(struct sk_buff *skb, int tailbits, struct sk_buff **trailer);
struct sk_buff *skb_dequeue(struct sk_buff_head *list);
void skb_free_datagram(struct sock *sk, struct sk_buff *skb);
void *skb_pull(struct sk_buff *skb, unsigned int len);
void *skb_pull_data(struct sk_buff *skb, size_t len);
void *skb_pull_rcsum(struct sk_buff *skb, unsigned int len);
void *skb_push(struct sk_buff *skb, unsigned int len);
void *skb_put(struct sk_buff *skb, unsigned int len);
void skb_queue_head(struct sk_buff_head *list, struct sk_buff *newsk);
void skb_queue_tail(struct sk_buff_head *list, struct sk_buff *newsk);
struct sk_buff *skb_recv_datagram(struct sock *sk, unsigned int flags, int *err);
void skb_scrub_packet(struct sk_buff *skb, bool xnet);
void skb_set_owner_w(struct sk_buff *skb, struct sock *sk);
void skb_trim(struct sk_buff *skb, unsigned int len);
void skb_unlink(struct sk_buff *skb, struct sk_buff_head *list);
char * skip_spaces(const char *);
void slhc_free(struct slcompress *comp);
struct slcompress *slhc_init(int rslots, int tslots);
int slhc_remember(struct slcompress *comp, unsigned char *icp, int isize);
int slhc_toss(struct slcompress *comp);
int slhc_uncompress(struct slcompress *comp, unsigned char *icp, int isize);
int snd_soc_register_card(struct snd_soc_card *card);
struct file *sock_alloc_file(struct socket *sock, int flags, const char *dname);
return sock_alloc_send_pskb(sk, size, 0, noblock, errcode, 0);
int sock_create_kern(struct net *net, int family, int type, int proto, struct socket **res);
int sock_diag_register(const struct sock_diag_handler *h);
void sock_diag_save_cookie(struct sock *sk, __u32 *cookie);
void sock_diag_unregister(const struct sock_diag_handler *h);
void sock_efree(struct sk_buff *skb);
unsigned long sock_i_ino(struct sock *sk);
kuid_t sock_i_uid(struct sock *sk);
void sock_init_data(struct socket *sock, struct sock *sk);
int sock_no_accept(struct socket *, struct socket *, int, bool);
int sock_no_bind(struct socket *, struct sockaddr *, int);
int sock_no_connect(struct socket *, struct sockaddr *, int, int);
int sock_no_getname(struct socket *, struct sockaddr *, int);
int sock_no_ioctl(struct socket *, unsigned int, unsigned long);
int sock_no_listen(struct socket *, int);
int sock_no_recvmsg(struct socket *, struct msghdr *, size_t, int);
int sock_no_sendmsg(struct socket *, struct msghdr *, size_t);
int sock_no_shutdown(struct socket *, int);
int sock_no_socketpair(struct socket *, struct socket *);
int sock_recvmsg(struct socket *sock, struct msghdr *msg, int flags);
int sock_register(const struct net_proto_family *fam);
void sock_release(struct socket *sock);
void sock_rfree(struct sk_buff *skb);
void sock_unregister(int family);
struct socket *sockfd_lookup(int fd, int *err);
void static_key_slow_dec(struct static_key *key);
bool static_key_slow_inc(struct static_key *key);
size_t strlcat(char *, const char *, __kernel_size_t);
ssize_t strscpy_pad(char *dest, const char *src, size_t count);
char * strsep(char **,const char *);
int submit_bio_wait(struct bio *bio);
int sync_blockdev(struct block_device *bdev);
void synchronize_irq(unsigned int irq);
void synchronize_net(void);
void synchronize_srcu(struct srcu_struct *ssp);
return sysfs_create_file_ns(kobj, attr, NULL);
bool sysfs_streq(const char *s1, const char *s2);
void tasklet_kill(struct tasklet_struct *t);
void tasklet_unlock_wait(struct tasklet_struct *t);
void tcp_read_done(struct sock *sk, size_t len);
struct sk_buff *tcp_recv_skb(struct sock *sk, u32 seq, u32 *off);
int tcp_register_ulp(struct tcp_ulp_ops *type);
int tcp_sendmsg_locked(struct sock *sk, struct msghdr *msg, size_t size);
void tcp_unregister_ulp(struct tcp_ulp_ops *type);
u64 timecounter_read(struct timecounter *tc);
int timer_delete_sync(struct timer_list *timer);
int timer_shutdown_sync(struct timer_list *timer);
void trace_event_printf(struct trace_iterator *iter, const char *fmt, ...);
int trace_event_raw_init(struct trace_event_call *call);
enum print_line_t trace_handle_return(struct trace_seq *s);
void tty_driver_kref_put(struct tty_driver *driver);
void tty_flip_buffer_push(struct tty_port *port);
unsigned char tty_get_char_size(unsigned int cflag);
void tty_hangup(struct tty_struct *tty);
void tty_kref_put(struct tty_struct *tty);
void tty_ldisc_deref(struct tty_ldisc *);
void tty_ldisc_flush(struct tty_struct *tty);
struct tty_ldisc *tty_ldisc_ref(struct tty_struct *);
int tty_mode_ioctl(struct tty_struct *tty, unsigned int cmd, unsigned long arg);
void tty_port_destroy(struct tty_port *port);
void tty_port_hangup(struct tty_port *port);
void tty_port_init(struct tty_port *port);
void tty_port_put(struct tty_port *port);
struct tty_struct *tty_port_tty_get(struct tty_port *port);
void tty_port_tty_hangup(struct tty_port *port, bool check_clocal);
void tty_port_tty_wakeup(struct tty_port *port);
int tty_register_driver(struct tty_driver *driver);
int tty_register_ldisc(struct tty_ldisc_ops *new_ldisc);
int tty_set_termios(struct tty_struct *tty, struct ktermios *kt);
speed_t tty_termios_baud_rate(const struct ktermios *termios);
void tty_termios_copy_hw(struct ktermios *new, const struct ktermios *old);
void tty_unregister_device(struct tty_driver *driver, unsigned index);
void tty_unregister_driver(struct tty_driver *driver);
void tty_unregister_ldisc(struct tty_ldisc_ops *ldisc);
void tty_unthrottle(struct tty_struct *tty);
void tty_vhangup(struct tty_struct *tty);
void tty_wakeup(struct tty_struct *tty);
return udp_sock_create4(net, cfg, sockp);
return udp_sock_create6(net, cfg, sockp);
void unlock_page(struct page *page);
void unpin_user_pages(struct page **pages, unsigned long npages);
void unregister_candev(struct net_device *dev);
void unregister_shrinker(struct shrinker *shrinker);
void up_read(struct rw_semaphore *sem);
void up_write(struct rw_semaphore *sem);
void usb_anchor_urb(struct urb *urb, struct usb_anchor *anchor);
int usb_clear_halt(struct usb_device *dev, int pipe);
int usb_disabled(void);
void usb_enable_lpm(struct usb_device *udev);
struct usb_device *usb_get_dev(struct usb_device *dev);
struct urb *usb_get_from_anchor(struct usb_anchor *anchor);
struct usb_interface *usb_get_intf(struct usb_interface *intf);
struct urb *usb_get_urb(struct urb *urb);
void usb_mon_deregister(void);
int usb_mon_register(const struct usb_mon_operations *ops);
void usb_poison_urb(struct urb *urb);
void usb_put_dev(struct usb_device *dev);
void usb_put_intf(struct usb_interface *intf);
void usb_register_notify(struct notifier_block *nb);
int usb_reset_device(struct usb_device *dev);
int usb_set_configuration(struct usb_device *dev, int configuration);
int usb_set_interface(struct usb_device *dev, int ifnum, int alternate);
ssize_t usb_show_dynids(struct usb_dynids *dynids, char *buf);
int usb_unlink_urb(struct urb *urb);
void usb_unpoison_urb(struct urb *urb);
void usb_unregister_notify(struct notifier_block *nb);
int usbnet_cdc_bind(struct usbnet *, struct usb_interface *);
void usbnet_cdc_status(struct usbnet *, struct urb *);
void usbnet_cdc_unbind(struct usbnet *, struct usb_interface *);
int usbnet_change_mtu(struct net_device *net, int new_mtu);
void usbnet_defer_kevent(struct usbnet *, int);
void usbnet_disconnect(struct usb_interface *);
void usbnet_get_drvinfo(struct net_device *, struct ethtool_drvinfo *);
int usbnet_get_endpoints(struct usbnet *, struct usb_interface *);
u32 usbnet_get_link(struct net_device *net);
u32 usbnet_get_msglevel(struct net_device *);
void usbnet_link_change(struct usbnet *, bool, bool);
int usbnet_manage_power(struct usbnet *, int);
int usbnet_nway_reset(struct net_device *net);
int usbnet_open(struct net_device *net);
int usbnet_probe(struct usb_interface *, const struct usb_device_id *);
int usbnet_resume(struct usb_interface *);
void usbnet_set_msglevel(struct net_device *, u32);
void usbnet_set_rx_mode(struct net_device *net);
void usbnet_skb_return(struct usbnet *, struct sk_buff *);
int usbnet_stop(struct net_device *net);
int usbnet_suspend(struct usb_interface *, pm_message_t);
void usbnet_tx_timeout(struct net_device *net, unsigned int txqueue);
void usbnet_unlink_rx_urbs(struct usbnet *);
void v9fs_register_trans(struct p9_trans_module *m);
void v9fs_unregister_trans(struct p9_trans_module *m);
void virtio_break_device(struct virtio_device *dev);
void virtio_config_changed(struct virtio_device *dev);
int virtio_device_freeze(struct virtio_device *dev);
int virtio_device_restore(struct virtio_device *dev);
size_t virtio_max_dma_size(const struct virtio_device *vdev);
void virtio_reset_device(struct virtio_device *dev);
void virtqueue_disable_cb(struct virtqueue *vq);
bool virtqueue_enable_cb(struct virtqueue *vq);
void *virtqueue_get_buf(struct virtqueue *vq, unsigned int *len);
bool virtqueue_is_broken(const struct virtqueue *vq);
bool virtqueue_kick(struct virtqueue *vq);
bool virtqueue_notify(struct virtqueue *vq);
u16 vlan_dev_vlan_id(const struct net_device *dev);
bool vlan_uses_dev(const struct net_device *dev);
int vlan_vid_add(struct net_device *dev, __be16 proto, u16 vid);
void vlan_vid_del(struct net_device *dev, __be16 proto, u16 vid);
int vm_iomap_memory(struct vm_area_struct *vma, phys_addr_t start, unsigned long len);
u8 vp_legacy_get_status(struct virtio_pci_legacy_device *ldev);
int vp_legacy_probe(struct virtio_pci_legacy_device *ldev);
void vp_legacy_remove(struct virtio_pci_legacy_device *ldev);
u32 vp_modern_generation(struct virtio_pci_modern_device *mdev);
u8 vp_modern_get_status(struct virtio_pci_modern_device *mdev);
int vp_modern_probe(struct virtio_pci_modern_device *mdev);
void vp_modern_remove(struct virtio_pci_modern_device *mdev);
void vring_del_virtqueue(struct virtqueue *vq);
irqreturn_t vring_interrupt(int irq, void *_vq);
int vscnprintf(char *buf, size_t size, const char *fmt, va_list args);
int vsock_core_register(const struct vsock_transport *t, int features);
void vsock_core_unregister(const struct vsock_transport *t);
long wait_woken(struct wait_queue_entry *wq_entry, unsigned mode, long timeout);
void wake_up_bit(void *word, int bit);
int wake_up_process(struct task_struct *tsk);
int woken_wake_function(struct wait_queue_entry *wq_entry, unsigned mode, int sync, void *key);
unsigned int work_busy(struct work_struct *work);
void wpan_phy_free(struct wpan_phy *phy);
int wpan_phy_register(struct wpan_phy *phy);
void wpan_phy_unregister(struct wpan_phy *phy);
int zlib_deflate (z_streamp strm, int flush);
int zlib_deflateEnd (z_streamp strm);
int zlib_deflateReset (z_streamp strm);
int zlib_inflate (z_streamp strm, int flush);
int zlib_inflateIncomp (z_stream *strm);
int zlib_inflateInit2(z_streamp strm, int windowBits);
int zlib_inflateReset (z_streamp strm);
unsigned long zs_compact(struct zs_pool *pool);
struct zs_pool *zs_create_pool(const char *name);
void zs_destroy_pool(struct zs_pool *pool);
void zs_free(struct zs_pool *pool, unsigned long obj);
unsigned long zs_get_total_pages(struct zs_pool *pool);
size_t zs_huge_class_size(struct zs_pool *pool);
unsigned int zs_lookup_class_index(struct zs_pool *pool, unsigned int size);
unsigned long zs_malloc(struct zs_pool *pool, size_t size, gfp_t flags);
void zs_pool_stats(struct zs_pool *pool, struct zs_pool_stats *stats);
void zs_unmap_object(struct zs_pool *pool, unsigned long handle);
void kfree_skb_reason(void);
void dev_addr_mod(void);
void alloc_workqueue(void);
void sock_no_mmap(void);
void _raw_spin_lock_irq(void);
void kasan_flag_enabled(void);
void trace_event_reg(void);
void skb_copy_expand(void);
void sk_alloc(void);
void lowpan_nhc_add(void);
void lowpan_nhc_del(void);
void datagram_poll(void);
void __nla_parse(void);
void alloc_netdev_mqs(void);
void bpf_trace_run3(void);
void bpf_trace_run4(void);
void kmem_cache_create(void);
void usbnet_read_cmd(void);
void sock_gettstamp(void);
void hrtimer_init(void);
void skb_tstamp_tx(void);
void log_write_mmio(void);
void log_post_write_mmio(void);
void tasklet_setup(void);
void kstrdup(void);
void usbnet_start_xmit(void);
void usleep_range_state(void);
void usbnet_write_cmd(void);
void __sock_recv_cmsgs(void);
void log_read_mmio(void);
void log_post_read_mmio(void);
void alloc_etherdev_mqs(void);
void memstart_addr(void);
void genlmsg_put(void);
void crypto_aead_setkey(void);
void iov_iter_kvec(void);
void usbnet_read_cmd_nopm(void);
void __hci_cmd_sync(void);
void can_rx_unregister(void);
void can_rx_register(void);
void __tty_alloc_driver(void);
void tty_port_open(void);
void tty_port_close(void);
void usb_ifnum_to_if(void);
void cdc_parse_cdc_header(void);
void kernel_sendmsg(void);
void kunit_running(void);
void kunit_hooks(void);
void skb_to_sgvec(void);
void __unregister_chrdev(void);
void virtqueue_add_inbuf(void);
void netdev_upper_dev_link(void);
void proc_create_net_data(void);
void idr_alloc_u32(void);
void generic_mii_ioctl(void);
void usbnet_write_cmd_nopm(void);
void rfkill_alloc(void);
void __sock_recv_timestamp(void);
void device_move(void);
void __hci_cmd_send(void);
void netif_napi_add_weight(void);
void sock_recv_errqueue(void);
void tty_standard_install(void);
void usb_control_msg_recv(void);
void __kfifo_out(void);
void usb_string(void);
void bt_procfs_init(void);
void bt_sock_alloc(void);
void dev_set_mac_address(void);
void kernel_connect(void);
void setup_udp_tunnel_sock(void);
void class_dev_iter_init(void);
void netdev_printk(void);
void __init_rwsem(void);
void device_for_each_child(void);
void __regmap_init(void);
void alloc_skb_with_frags(void);
void register_shrinker(void);
void virtqueue_add_outbuf(void);
void __register_blkdev(void);
void virtqueue_add_sgs(void);
void dev_change_flags(void);
void netif_inherit_tso_max(void);
void vlan_filter_push_vids(void);
void vlan_filter_drop_vids(void);
void __nla_validate(void);
void dev_get_stats(void);
void __sock_create(void);
void p9_parse_header(void);
void mii_check_media(void);
void phylink_create(void);
void net_selftest(void);
void phy_connect(void);
void seq_hlist_start_head(void);
void seq_hlist_next(void);
void memcpy_and_pad(void);
void aes_expandkey(void);
void crypto_shash_setkey(void);
void dev_coredumpv(void);
void debugfs_attr_read(void);
void debugfs_attr_write(void);
void efi(void);
void __hci_cmd_sync_ev(void);
void sdio_writesb(void);
void sdio_writeb(void);
void sdio_readsb(void);
void of_get_child_by_name(void);
void rtnl_register_module(void);
void sock_cmsg_send(void);
void usb_alloc_coherent(void);
void usb_free_coherent(void);
void dev_addr_add(void);
void dev_addr_del(void);
void tipc_nl_sk_walk(void);
void tipc_dump_start(void);
void tipc_dump_done(void);
void fat_time_fat2unix(void);
void fat_time_unix2fat(void);
void tty_encode_baud_rate(void);
void __bitmap_complement(void);
void anon_inode_getfd(void);
void kimage_voffset(void);
void pin_user_pages(void);
void arm_smccc_1_2_hvc(void);
void __percpu_init_rwsem(void);
void n_tty_ioctl_helper(void);
void btbcm_set_bdaddr(void);
void btbcm_check_bdaddr(void);
void regulator_bulk_enable(void);
void btbcm_initialize(void);
void btbcm_finalize(void);
void qca_read_soc_version(void);
void qca_uart_setup(void);
void qca_set_bdaddr(void);
void qca_set_bdaddr_rome(void);
void hci_devcd_register(void);
void usb_interrupt_msg(void);
void hid_input_report(void);
void class_for_each_device(void);
void dev_getbyhwaddr_rcu(void);
void sock_common_recvmsg(void);
void sysfs_create_bin_file(void);
void sysfs_remove_bin_file(void);
void kunit_remove_action(void);
void kunit_release_action(void);
void pfn_is_map_memory(void);
void udp_set_csum(void);
void udp6_set_csum(void);
void l2tp_session_get_nth(void);
void l2tp_tunnel_get_nth(void);
void l2tp_udp_encap_recv(void);
void l2tp_session_delete(void);
void l2tp_tunnel_get(void);
void l2tp_tunnel_create(void);
void l2tp_tunnel_register(void);
void l2tp_tunnel_delete(void);
void l2tp_session_create(void);
void l2tp_session_register(void);
void sock_wmalloc(void);
void l2tp_xmit_skb(void);
void wpan_phy_new(void);
void nl802154_scan_done(void);
void nl802154_scan_started(void);
void nl802154_scan_event(void);
void dev_fetch_sw_netstats(void);
void devm_memremap(void);
void zlib_deflateInit2(void);
void slhc_compress(void);
void iov_iter_init(void);
void skb_realloc_headroom(void);
void kthread_create_worker(void);
void pps_register_source(void);
void pps_event(void);
void timecounter_init(void);
void timecounter_cyc2time(void);
void ptp_clock_register(void);
void crypto_shash_digest(void);
void skb_add_rx_frag(void);
void kmalloc_node_trace(void);
void regmap_register_patch(void);
void regcache_drop_region(void);
void regmap_raw_read(void);
void __regmap_init_ram(void);
void __regmap_init_raw_ram(void);
void hci_conn_security(void);
void tty_port_install(void);
void usb_control_msg_send(void);
void alloc_candev_mqs(void);
void alloc_can_err_skb(void);
void can_change_state(void);
void snd_soc_add_component(void);
void skb_try_coalesce(void);
void __rb_insert_augmented(void);
void __rb_erase_color(void);
void rht_bucket_nested(void);
void rhashtable_init(void);
void sk_reset_timer(void);
void __rht_bucket_nested(void);
void ipv6_dev_find(void);
void dst_cache_set_ip4(void);
void udp_tunnel_xmit_skb(void);
void ipv6_stub(void);
void dst_cache_set_ip6(void);
void udp_tunnel6_xmit_skb(void);
void iov_iter_bvec(void);
void tcp_poll(void);
void sk_msg_alloc(void);
void sk_msg_clone(void);
void sk_psock_msg_verdict(void);
void tcp_bpf_sendmsg_redir(void);
void iov_iter_get_pages2(void);
void sk_msg_recvmsg(void);
void skb_splice_bits(void);
void bpf_trace_run5(void);
void bpf_trace_run6(void);
void tcp_read_sock(void);
void kfree_skb_list_reason(void);
void usb_match_id(void);
void usb_match_one_id(void);
void __kfifo_alloc(void);
void __kfifo_in(void);
void usb_store_new_id(void);
void __devm_alloc_percpu(void);
void init_on_free(void);
void balloon_page_enqueue(void);
void page_relinquish(void);
void vm_event_states(void);
void __blk_mq_alloc_disk(void);
void string_get_size(void);
void sg_free_table_chained(void);
void blk_mq_alloc_request(void);
void blk_rq_map_kern(void);
void hvc_instantiate(void);
void __hvc_resize(void);
void hvc_remove(void);
void hvc_alloc(void);
void hvc_poll(void);
void hvc_kick(void);
void __splice_from_pipe(void);
void vp_modern_set_status(void);
void __pci_register_driver(void);
void vp_legacy_set_status(void);
void pci_iomap_range(void);
void rtnl_create_link(void);
void rtnl_configure_link(void);
void crypto_comp_compress(void);
void idr_for_each(void);
void zs_map_object(void);
void flush_dcache_page(void);
void __bio_add_page(void);
void blkdev_get_by_dev(void);
void bio_init(void);
return __cpuhp_state_add_instance(state, node, true);
return __cpuhp_state_remove_instance(state, node, true);
return __dev_change_net_namespace(dev, net, pat, 0);
u32 __get_random_u32_below(u32 ceil);
return __irq_apply_affinity_hint(irq, m, false);
void __mmap_lock_do_trace_released(struct mm_struct *mm, bool write);
void __mmap_lock_do_trace_start_locking(struct mm_struct *mm, bool write);
void __page_pinner_put_page(struct page *page);
int __pm_runtime_set_status(struct device *dev, unsigned int status);
void __pm_runtime_use_autosuspend(struct device *dev, bool use);
struct device *__root_device_register(const char *name, struct module *owner);
int __serdev_device_driver_register(struct serdev_device_driver *, struct module *);
bool __trace_trigger_soft_disabled(struct trace_event_file *file);
return __tty_insert_flip_string_flags(port, chars, &flag, false, size);
void _snd_pcm_hw_params_any(struct snd_pcm_hw_params *params);
void add_wait_queue_exclusive(struct wait_queue_head *wq_head, struct wait_queue_entry *wq_entry);
void add_wait_queue_priority(struct wait_queue_head *wq_head, struct wait_queue_entry *wq_entry);
void adjust_managed_page_count(struct page *page, long count);
return bio_end_io_acct_remapped(bio, start_time, bio->bi_bdev);
bool blk_mq_complete_request_remote(struct request *rq);
void blk_mq_end_request_batch(struct io_comp_batch *ib);
void blk_mq_quiesce_queue_nowait(struct request_queue *q);
void blk_mq_unquiesce_queue(struct request_queue *q);
void blk_queue_chunk_sectors(struct request_queue *, unsigned int);
void bt_sock_reclassify_lock(struct sock *sk, int proto);
int call_netdevice_notifiers(unsigned long val, struct net_device *dev);
return can_dropped_invalid_skb(dev, skb);
unsigned int clk_hw_get_num_parents(const struct clk_hw *hw);
int clk_notifier_unregister(struct clk *clk, struct notifier_block *nb);
return clocks_calc_mult_shift(&ce->mult, &ce->shift, NSEC_PER_SEC, freq, maxsec);
int crypto_aead_setauthsize(struct crypto_aead *tfm, unsigned int authsize);
int crypto_ecdh_encode_key(char *buf, unsigned int len, const struct ecdh *p);
int crypto_get_default_rng(void);
void crypto_put_default_rng(void);
int crypto_skcipher_decrypt(struct skcipher_request *req);
int crypto_skcipher_encrypt(struct skcipher_request *req);
return crypto_skcipher_setkey(&tfm->base, key, keylen);
void dev_kfree_skb_any_reason(struct sk_buff *skb, enum skb_drop_reason reason);
void dev_kfree_skb_irq_reason(struct sk_buff *skb, enum skb_drop_reason reason);
bool device_property_present(const struct device *dev, const char *propname);
return device_property_read_u32_array(dev, propname, val, 1);
return device_property_read_u8_array(dev, propname, val, 1);
void device_set_wakeup_capable(struct device *dev, bool capable);
int device_set_wakeup_enable(struct device *dev, bool enable);
struct clk *devm_clk_get_optional_enabled(struct device *dev, const char *id);
void do_trace_netlink_extack(const char *msg);
int eth_platform_get_mac_address(struct device *dev, u8 *mac_addr);
int ethtool_op_get_ts_info(struct net_device *dev, struct ethtool_ts_info *eti);
return fwnode_property_read_u8_array(fwnode, propname, val, 1);
int genl_unregister_family(const struct genl_family *family);
int gpiod_get_value_cansleep(const struct gpio_desc *desc);
void gpiod_set_value_cansleep(struct gpio_desc *desc, int value);
int hci_devcd_append_pattern(struct hci_dev *hdev, u8 pattern, u32 len);
int ieee802154_max_payload(const struct ieee802154_hdr *hdr);
bool kthread_cancel_delayed_work_sync(struct kthread_delayed_work *work);
void kthread_delayed_work_timer_fn(struct timer_list *t);
void kthread_destroy_worker(struct kthread_worker *worker);
void kunit_deactivate_static_stub(struct kunit *test, void *real_fn_addr);
void lowpan_unregister_netdevice(struct net_device *dev);
return mutex_lock_interruptible(&dev->mutex);
int net_selftest_get_count(void);
void net_selftest_get_strings(u8 *data);
void netdev_rx_handler_unregister(struct net_device *dev);
void netdev_update_features(struct net_device *dev);
void netif_set_tso_max_size(struct net_device *dev, unsigned int size);
int netlink_register_notifier(struct notifier_block *nb);
int netlink_unregister_notifier(struct notifier_block *nb);
return of_find_node_opts_by_path(path, NULL);
return of_property_read_string_helper(np, propname, out_strs, sz, 0);
struct reserved_mem *of_reserved_mem_lookup(struct device_node *np);
int out_of_line_wait_on_bit(void *word, int, wait_bit_action_f *action, unsigned int mode);
int out_of_line_wait_on_bit_timeout(void *word, int, wait_bit_action_f *action, unsigned int mode, unsigned long timeout);
int page_reporting_register(struct page_reporting_dev_info *prdev);
void page_reporting_unregister(struct page_reporting_dev_info *prdev);
u16 pci_find_ext_capability(struct pci_dev *dev, int cap);
u8 pci_find_next_capability(struct pci_dev *dev, u8 pos, int cap);
void pci_release_selected_regions(struct pci_dev *, int);
int pci_request_selected_regions(struct pci_dev *, int, const char *);
int phy_ethtool_nway_reset(struct net_device *ndev);
void phylink_disconnect_phy(struct phylink *);
void posix_clock_unregister(struct posix_clock *clk);
int ppp_register_compressor(struct compressor *);
int ppp_register_net_channel(struct net *, struct ppp_channel *);
void ppp_unregister_channel(struct ppp_channel *);
void ppp_unregister_compressor(struct compressor *);
int proc_doulongvec_minmax(struct ctl_table *, int, void *, size_t *, loff_t *);
int register_module_notifier(struct notifier_block *nb);
int register_netdevice_notifier(struct notifier_block *nb);
int register_pernet_device(struct pernet_operations *);
int register_pernet_subsys(struct pernet_operations *);
int register_virtio_device(struct virtio_device *dev);
int register_virtio_driver(struct virtio_driver *drv);
return rhashtable_insert_slow(ht, key, obj);
int rhashtable_walk_start_check(struct rhashtable_iter *iter);
void root_device_unregister(struct device *root);
long schedule_timeout_interruptible(long timeout);
long schedule_timeout_uninterruptible(long timeout);
void sdio_unregister_driver(struct sdio_driver *);
void security_release_secctx(char *secdata, u32 seclen);
int security_secid_to_secctx(u32 secid, char **secdata, u32 *seclen);
int serdev_device_get_tiocm(struct serdev_device *);
unsigned int serdev_device_set_baudrate(struct serdev_device *, unsigned int);
void serdev_device_set_flow_control(struct serdev_device *, bool);
int serdev_device_set_tiocm(struct serdev_device *, int, int);
void serdev_device_wait_until_sent(struct serdev_device *, long);
int serdev_device_write_buf(struct serdev_device *, const unsigned char *, size_t);
void serdev_device_write_flush(struct serdev_device *);
bool set_capacity_and_notify(struct gendisk *disk, sector_t size);
void set_normalized_timespec64(struct timespec64 *ts, time64_t sec, s64 nsec);
int sk_psock_tls_strp_read(struct sk_psock *psock, struct sk_buff *skb);
return skb_copy_datagram_iter(from, offset, &msg->msg_iter, size);
int snd_soc_params_to_bclk(struct snd_pcm_hw_params *parms);
int snd_soc_tplg_component_remove(struct snd_soc_component *comp);
void snd_soc_unregister_card(struct snd_soc_card *card);
void snd_soc_unregister_component(struct device *dev);
return sock_queue_rcv_skb_reason(sk, skb, NULL);
void tcp_rate_check_app_limited(struct sock *sk);
void trace_event_buffer_commit(struct trace_event_buffer *fbuffer);
void tty_driver_flush_buffer(struct tty_struct *tty);
void udp_tunnel_sock_release(struct socket *sock);
int unregister_module_notifier(struct notifier_block *nb);
void unregister_net_sysctl_table(struct ctl_table_header *header);
void unregister_netdevice_many(struct list_head *head);
int unregister_netdevice_notifier(struct notifier_block *nb);
void unregister_netdevice_queue(struct net_device *dev, struct list_head *head);
int unregister_oom_notifier(struct notifier_block *nb);
void unregister_pernet_device(struct pernet_operations *);
void unregister_pernet_subsys(struct pernet_operations *);
int unregister_pm_notifier(struct notifier_block *nb);
void unregister_pppox_proto(int proto_num);
void unregister_virtio_device(struct virtio_device *dev);
void unregister_virtio_driver(struct virtio_driver *drv);
int usb_autopm_get_interface(struct usb_interface *intf);
int usb_autopm_get_interface_async(struct usb_interface *intf);
void usb_autopm_get_interface_no_resume(struct usb_interface *intf);
void usb_autopm_put_interface(struct usb_interface *intf);
void usb_autopm_put_interface_async(struct usb_interface *intf);
void usb_deregister_device_driver(struct usb_device_driver *);
int usb_driver_set_configuration(struct usb_device *udev, int config);
return usb_find_common_endpoints(alt, bulk_in, NULL, NULL, NULL);
void usb_queue_reset_device(struct usb_interface *dev);
int usb_reset_configuration(struct usb_device *dev);
void usb_serial_deregister_drivers(struct usb_serial_driver *const serial_drivers[]);
int usb_serial_generic_get_icount(struct tty_struct *tty, struct serial_icounter_struct *icount);
int usb_serial_generic_open(struct tty_struct *tty, struct usb_serial_port *port);
void usb_serial_generic_throttle(struct tty_struct *tty);
int usb_serial_generic_tiocmiwait(struct tty_struct *tty, unsigned long arg);
void usb_serial_generic_unthrottle(struct tty_struct *tty);
void usbnet_cdc_update_filter(struct usbnet *dev);
void usbnet_device_suggests_idle(struct usbnet *dev);
int usbnet_get_ethernet_addr(struct usbnet *, int);
void usbnet_update_max_qlen(struct usbnet *dev);
int virtio_transport_connect(struct vsock_sock *vsk);
void virtio_transport_deliver_tap_pkt(struct sk_buff *skb);
void virtio_transport_destruct(struct vsock_sock *vsk);
bool virtio_transport_dgram_allow(u32 cid, u32 port);
void virtio_transport_notify_buffer_size(struct vsock_sock *vsk, u64 *val);
int virtio_transport_notify_set_rcvlowat(struct vsock_sock *vsk, int val);
int virtio_transport_purge_skbs(void *vsk, struct sk_buff_head *list);
int virtio_transport_read_skb(struct vsock_sock *vsk, skb_read_actor_t read_actor);
void virtio_transport_release(struct vsock_sock *vsk);
u32 virtio_transport_seqpacket_has_data(struct vsock_sock *vsk);
int virtio_transport_shutdown(struct vsock_sock *vsk, int mode);
bool virtio_transport_stream_allow(u32 cid, u32 port);
s64 virtio_transport_stream_has_data(struct vsock_sock *vsk);
s64 virtio_transport_stream_has_space(struct vsock_sock *vsk);
bool virtio_transport_stream_is_active(struct vsock_sock *vsk);
u64 virtio_transport_stream_rcvhiwat(struct vsock_sock *vsk);
void *virtqueue_detach_unused_buf(struct virtqueue *vq);
void virtqueue_disable_dma_api_for_buffers(struct virtqueue *vq);
dma_addr_t virtqueue_get_avail_addr(const struct virtqueue *vq);
dma_addr_t virtqueue_get_desc_addr(const struct virtqueue *vq);
dma_addr_t virtqueue_get_used_addr(const struct virtqueue *vq);
unsigned int virtqueue_get_vring_size(const struct virtqueue *vq);
bool virtqueue_kick_prepare(struct virtqueue *vq);
u64 vp_legacy_get_features(struct virtio_pci_legacy_device *ldev);
u64 vp_modern_get_features(struct virtio_pci_modern_device *mdev);
u16 vp_modern_get_num_queues(struct virtio_pci_modern_device *mdev);
int vp_modern_get_queue_reset(struct virtio_pci_modern_device *mdev, u16 index);
void vp_modern_set_queue_reset(struct virtio_pci_modern_device *mdev, u16 index);
u32 vring_notification_data(struct virtqueue *_vq);
void vring_transport_features(struct virtio_device *vdev);
int zlib_deflate_workspacesize (int windowBits, int memLevel);
int zlib_inflate_workspacesize (void);
void skb_queue_purge_reason(void);
void trace_event_buffer_reserve(void);
void perf_trace_run_bpf_submit(void);
void hrtimer_start_range_ns(void);
void __tracepoint_rwmmio_write(void);
void __tracepoint_rwmmio_post_write(void);
void trace_print_symbols_seq(void);
void of_property_read_variable_u32_array(void);
void __tracepoint_rwmmio_read(void);
void __tracepoint_rwmmio_post_read(void);
void usb_driver_claim_interface(void);
void usb_driver_release_interface(void);
void virtio_check_driver_offered_feature(void);
void usbnet_write_cmd_async(void);
void mii_ethtool_get_link_ksettings(void);
void __init_swait_queue_head(void);
void simple_read_from_buffer(void);
void tty_port_register_device(void);
void kunit_mem_assert_format(void);
void kthread_create_on_node(void);
void __tracepoint_sk_data_ready(void);
void __traceiter_sk_data_ready(void);
void netdev_upper_dev_unlink(void);
void netif_stacked_transfer_operstate(void);
void mii_ethtool_set_link_ksettings(void);
void __sock_recv_wifi_status(void);
void proc_create_net_single(void);
void usbnet_get_link_ksettings_internal(void);
void ieee802154_hdr_peek_addrs(void);
void register_net_sysctl_sz(void);
void ethtool_convert_legacy_u32_to_link_mode(void);
void usb_check_bulk_endpoints(void);
void blk_queue_max_discard_sectors(void);
void blk_queue_max_write_zeroes_sectors(void);
void addrconf_add_linklocal(void);
void __ndisc_fill_addr_option(void);
void addrconf_prefix_rcv_add_addr(void);
void generic_hwtstamp_get_lower(void);
void generic_hwtstamp_set_lower(void);
void __ethtool_get_link_ksettings(void);
void kmem_cache_create_usercopy(void);
void phylink_ethtool_get_pauseparam(void);
void phylink_ethtool_set_pauseparam(void);
void usbnet_get_link_ksettings_mii(void);
void usbnet_set_link_ksettings_mii(void);
void phy_ethtool_get_link_ksettings(void);
void phy_ethtool_set_link_ksettings(void);
void* proc_create_seq_private(void);
void crypto_shash_tfm_digest(void);
void firmware_request_nowarn(void);
void __kmalloc_node_track_caller(void);
void devm_platform_ioremap_resource(void);
void usb_altnum_to_altsetting(void);
void clk_hw_init_rate_request(void);
void __clk_mux_determine_rate_closest(void);
void clk_hw_determine_rate_no_reparent(void);
void tipc_sk_fill_sock_diag(void);
void usb_serial_register_drivers(void);
void gpiochip_add_data_with_key(void);
void usb_serial_handle_dcd_change(void);
void __tracepoint_android_vh_gzvm_destroy_vm_post_process(void);
void unpin_user_pages_dirty_lock(void);
void __traceiter_android_vh_gzvm_destroy_vm_post_process(void);
void __tracepoint_android_vh_gzvm_vcpu_exit_reason(void);
void __traceiter_android_vh_gzvm_vcpu_exit_reason(void);
void eventfd_ctx_remove_wait_queue(void);
void __tracepoint_mmap_lock_start_locking(void);
void __tracepoint_mmap_lock_acquire_returned(void);
void __tracepoint_mmap_lock_released(void);
void __mmap_lock_do_trace_acquire_returned(void);
void __tracepoint_android_vh_gzvm_handle_demand_page_pre(void);
void __tracepoint_android_vh_gzvm_handle_demand_page_post(void);
void __traceiter_android_vh_gzvm_handle_demand_page_pre(void);
void __traceiter_android_vh_gzvm_handle_demand_page_post(void);
void _trace_android_vh_record_pcpu_rwsem_starttime(void);
void tty_termios_encode_baud_rate(void);
void devm_regulator_bulk_get(void);
void regulator_bulk_disable(void);
void btbcm_read_pcm_int_params(void);
void btbcm_write_pcm_int_params(void);
void device_property_read_string(void);
void qca_send_pre_shutdown_cmd(void);
void __module_put_and_kthread_exit(void);
void lowpan_register_netdevice(void);
void lowpan_header_decompress(void);
void inet_frag_queue_insert(void);
void inet_frag_reasm_prepare(void);
void inet_frag_reasm_finish(void);
void lowpan_header_compress(void);
void sock_common_setsockopt(void);
void sock_common_getsockopt(void);
void __kunit_activate_static_stub(void);
void kunit_destroy_resource(void);
void kthread_complete_and_exit(void);
void l2tp_session_dec_refcount(void);
void l2tp_tunnel_dec_refcount(void);
void l2tp_tunnel_inc_refcount(void);
void l2tp_tunnel_get_session(void);
void l2tp_session_inc_refcount(void);
void l2tp_session_set_header_len(void);
void ieee802154_mac_cmd_pl_pull(void);
void crypto_alloc_sync_skcipher(void);
void ieee802154_mac_cmd_push(void);
void ieee802154_beacon_push(void);
void nl802154_beaconing_done(void);
void netdev_rx_handler_register(void);
void ethtool_convert_link_mode_to_legacy_u32(void);
void __platform_driver_probe(void);
void security_sk_classify_flow(void);
void kthread_queue_delayed_work(void);
void kthread_mod_delayed_work(void);
void device_for_each_child_reverse(void);
void kvm_arm_hyp_service_available(void);
void kvm_arch_ptp_get_crosststamp(void);
void get_device_system_crosststamp(void);
void usb_register_device_driver(void);
void bt_sock_stream_recvmsg(void);
void usb_check_int_endpoints(void);
void snd_soc_component_initialize(void);
void snd_soc_tplg_component_load(void);
void snd_soc_tdm_params_to_bclk(void);
void rht_bucket_nested_insert(void);
void sk_msg_zerocopy_from_iter(void);
void sk_msg_memcopy_from_iter(void);
void iov_iter_extract_pages(void);
void memory_cgrp_subsys_on_dfl_key(void);
void devm_platform_get_and_ioremap_resource(void);
void post_page_relinquish_tlb_inv(void);
void blk_queue_alignment_offset(void);
void blk_queue_max_secure_erase_sectors(void);
void blk_queue_max_discard_segments(void);
void blk_revalidate_disk_zones(void);
void blk_queue_max_zone_append_sectors(void);
void blk_mq_virtio_map_queues(void);
void sg_alloc_table_chained(void);
void vp_modern_config_vector(void);
void vp_modern_get_queue_size(void);
void vp_modern_get_queue_enable(void);
void vring_create_virtqueue(void);
void vp_modern_map_vq_notify(void);
void vp_modern_queue_vector(void);
void vp_modern_set_queue_enable(void);
void vp_modern_set_features(void);
void vp_modern_set_queue_size(void);
void vp_modern_queue_address(void);
void pci_alloc_irq_vectors_affinity(void);
void vp_legacy_config_vector(void);
void vp_legacy_get_queue_size(void);
void vp_legacy_get_queue_enable(void);
void vp_legacy_set_queue_address(void);
void vp_legacy_queue_vector(void);
void vp_legacy_set_features(void);
void virtio_transport_recv_pkt(void);
void vsock_for_each_connected_socket(void);
void virtio_transport_do_socket_init(void);
void virtio_transport_dgram_bind(void);
void virtio_transport_dgram_dequeue(void);
void virtio_transport_dgram_enqueue(void);
void virtio_transport_stream_dequeue(void);
void virtio_transport_stream_enqueue(void);
void virtio_transport_seqpacket_dequeue(void);
void virtio_transport_seqpacket_enqueue(void);
void virtio_transport_notify_poll_in(void);
void virtio_transport_notify_poll_out(void);
void virtio_transport_notify_recv_init(void);
void virtio_transport_notify_recv_pre_block(void);
void virtio_transport_notify_recv_pre_dequeue(void);
void virtio_transport_notify_recv_post_dequeue(void);
void virtio_transport_notify_send_init(void);
void virtio_transport_notify_send_pre_block(void);
void virtio_transport_notify_send_pre_enqueue(void);
void virtio_transport_notify_send_post_enqueue(void);
void device_find_child_by_name(void);
void crypto_comp_decompress(void);
void __tracepoint_android_vh_zs_shrinker_bypass(void);
void __tracepoint_android_vh_zs_shrinker_adjust(void);
void __traceiter_android_vh_zs_shrinker_bypass(void);
void __traceiter_android_vh_zs_shrinker_adjust(void);

extern struct cpumask __cpu_online_mask;
extern struct cpumask __cpu_possible_mask;
extern atomic_t __num_online_cpus;
extern const struct movable_operations balloon_mops;
extern struct dentry *bt_debugfs;
extern struct crypto_rng *crypto_default_rng;
extern struct bio_set fs_bio_set;
extern const struct in6_addr in6addr_any;
extern struct net init_net;
extern struct user_namespace init_user_ns;
extern struct uts_namespace init_uts_ns;
extern struct kobject *kernel_kobj;
extern struct neigh_table nd_tbl;
extern struct list_head net_namespace_list;
extern unsigned int nr_cpu_ids;
extern int overflowgid;
extern int overflowuid;
extern struct static_key_false page_pinner_inited;
extern const struct kernel_param_ops param_ops_bool;
extern const struct kernel_param_ops param_ops_charp;
extern const struct kernel_param_ops param_ops_int;
extern struct workqueue_struct *system_freezable_wq;
extern struct workqueue_struct *system_long_wq;
extern unsigned long tcp_memory_pressure;
extern struct ktermios tty_std_termios;
extern struct idr usb_bus_idr;
extern struct mutex usb_bus_idr_lock;
extern struct dentry *usb_debug_root;
extern struct static_key_false memcg_sockets_enabled_key;

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // DRIVERHUB_SRC_SHIM_KERNEL_GKI_STUBS_H_
